plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id "io.freefair.lombok" version "9.5.0"
}

group 'tech.aomi.common'
version '1.0.0_5-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}

repositories {
    mavenCentral()
    maven {
        url "https://nexus.stelarx.tech/repository/maven-snapshots/"
    }
}

dependencies {
    compileOnly "org.slf4j:slf4j-api:1.7.25"

    compileOnly "com.fasterxml.jackson.core:jackson-core:2.16.1"
    compileOnly "com.fasterxml.jackson.core:jackson-databind:2.16.1"

    compileOnly "com.google.code.gson:gson:2.10.1"

    compileOnly 'com.alibaba.fastjson2:fastjson2:2.0.47'

}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            versionMapping {
                allVariants {
                    fromResolutionResult()
                }
            }
        }
    }
    repositories {
        maven {
            url = project.version.endsWith('-SNAPSHOT')
                    ? 'https://nexus.stelarx.tech/repository/maven-snapshots/'
                    : 'https://nexus.stelarx.tech/repository/maven-releases/'
            credentials {
                username System.getenv('REPO_USERNAME')
                password System.getenv('REPO_PASSWORD')
            }
        }
    }
}
